version: '3'

services:
  webapplication1:
    image: webapplication1
    build:
      context: ./WebApplication1
      dockerfile: Dockerfile

  consoleapp1:
    image: consoleapp1
    build:
      context: ./ConsoleApp1
      dockerfile: Dockerfile
